### ISSUE TITLE
cannot use

### ISSUE THREAD

**Issue by Hubert21** [ITPrism/MagicGallery#1]
Hello,
I am in joomla 3.4
there is no module available in the list ; hence I cannot display anything on my page :/
Unfortunately the link to the doc is dead, and the prism library is told by avast as having a malware!
It'a a shame as the demo looks promising.

**Comment by ITPrism** [comment]
Hi,
Thank you for the post!

The link points to a page where you will be able to subscribe for on the members site. The modules are paid.
You can display your galleries creating menu item to a view on your website, using the component absolutely free.
You are right, the documentation missing. :) I forgot to write it because I was busy with other things. I am going to do it right now.
The prism library is clean. Your antivirus software detects it wrong because there are javascript in the package. If you would like, you can scan it with another antivirus software to be sure.
